cities:
  - Caerleon
  - Lymhurst
freshness:
  max_age_hours: 24

fees:
  sales_tax_premium: 0.04
  sales_tax_no_premium: 0.08
  setup_fee: 0.025

premium_enabled: true

risk:
  caerleon_high_risk: true

crafting:
  resource_return_rate: 0.15
  use_focus: false
  focus_return_rate: 0.35
  default_station_fee: 0

aodp:
  base_url: "https://www.albion-online-data.com/api/v2/stats"
  server: "europe"
  chunk_size: 40
  rate_delay_seconds: 1
  timeout_seconds: 30
uploader:
  enabled: true
  ingest_base: "http+pow://albion-online-data.com"
  enable_websocket: true
  interface: null        # auto
  no_cpu_limit: false
  binary_path_win: null  # optional override
  binary_path_linux: null
